// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package upstream

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/vitoramaral10/patchbay/internal/platform/webui"

// A caixa de colar o comando de instalação.
//
// Fica em arquivo próprio, e não em admin.templ, porque é um caminho de entrada
// à parte: não é o formulário de upstream com valores preenchidos, é um texto
// que o patchbay analisa e transforma em cadastro. O que grava é o texto,
// reanalisado no POST — a tela não monta campo nenhum.
//
// Até 2026-09-16 eram duas telas próprias (colar numa página, conferir noutra)
// e a criação vinha num terceiro passo. Viraram este cartão dentro da lista de
// MCPs: colar e salvar, por decisão do dono.

// rotaColar é a única rota do caminho de colar.
func rotaColar() string { return webui.RotaUpstreams + "/colar" }

// CaixaDeColar é o cartão de colar o comando, no topo da lista de MCPs.
func CaixaDeColar(d DadosColar) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"colar\" class=\"scroll-mt-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if d.Erro != "" {
			templ_7745c5c3_Err = webui.AlertaCaixa(webui.Alerta{
				Tom:    webui.TomPerigo,
				Titulo: "Não deu para usar este comando.",
				Texto:  d.Erro,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<form method=\"post\" action=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(rotaColar()))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/upstream/comando.templ`, Line: 30, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"flex flex-col gap-4 px-4 py-5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = webui.CampoTexto(webui.DadosCampo{
				Nome:   "comando",
				Rotulo: "Comando",
				Valor:  d.Texto,
				Ajuda: "Uma linha de claude mcp add, com ou sem o executável na frente. " +
					"Pode vir quebrada em várias linhas, como na documentação. " +
					"O patchbay lê o transporte, a URL ou o processo, os headers e o token, " +
					"e cria o MCP direto.",
				Placeholder: "claude mcp add --transport http exemplo https://exemplo.com/mcp " +
					"--header \"Authorization: Bearer o-seu-token\"",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p class=\"max-w-[65ch] text-sm text-conteudo-suave\">O token vai cifrado para o banco e não volta para esta tela. Se o comando ainda tiver o exemplo da documentação no lugar do token — algo como <code class=\"font-mono\">[your API token]</code> —, troque-o antes: gravado assim, o erro só apareceria como 401 dias depois.</p><p class=\"max-w-[65ch] text-sm text-conteudo-suave\"><strong>Comando de processo local é executado aqui.</strong> Uma linha que começa com <code class=\"font-mono\">npx</code> ou <code class=\"font-mono\">uvx</code> vira processo filho do patchbay, com o usuário deste processo, reiniciado pela supervisão sempre que cair. Não há tela de conferência antes: leia a linha antes de colar.</p><div><button type=\"submit\" class=\"pb-botao pb-botao-primario\">Criar MCP</button></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = webui.Cartao("Adicionar colando o comando de instalação").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
